spring:
  application:
    name: wantedmarket
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db
#    username: sa
#    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  jwt:
    secret: nwiniefddeubvbvbvmxqowfkeklllefkjunviznwmpepqqoeoqweriocpvmllseznqewvnmp

  sql:
    init:
      mode: always